### ISSUE TITLE
Question about qualitative evaluation of Until 

### ISSUE THREAD

**Issue by xian49930** [mvcisback/py-metric-temporal-logic#217]
Hi,

I have a question about the evaluation of Until when using this lib. I have tried the following example on Google Colab:

```
# !pip install metric-temporal-logic
import mtl

data = {
    'start': [(0, True), (1, False), (5, True), (6, True)],
    'success': [(0, False), (20, True)]
}
phi = mtl.parse('(start U[0,20] success)')
print(phi(data, time = None, quantitative=False))
# Output:
# [(0, False), (1, False), (5, False), (6, False), (20, True)]
```
From my understanding, the output at time 6 should be **True**, but the result I got is _**False**_. Could you help to understand it? Thanks.

**Comment by xian49930** [comment]
An update. The outputs from the following codes look weird. Could you also take a look? Thanks.

```
###########
# Example 1
data = {
    'start': [(0, True)],
    'success': [(20, True)]
}
phi = mtl.parse('(start U[0, 21] success)')
print(phi(data, time = None, quantitative=False))
# Output: [(0, True), (20, True)]

phi = mtl.parse('(start U[0, 20] success)')
print(phi(data, time = None, quantitative=False))
# Output: [(0, True), (20, True)]

###########
# Example 2
data = {
    'start': [(0, True)],
    'success': [(0, True), (20, True)]
}
phi = mtl.parse('(start U[0, 21] success)')
print(phi(data, time = None, quantitative=False))
# Output: [(0, True), (20, True)]

phi = mtl.parse('(start U[0, 20] success)')
print(phi(data, time = None, quantitative=False))
# Output: [(0, True), (20, True)]

###########
# Example 3
data = {
    'start': [(0, True)],
    'success': [(0, False), (20, True)]
}
phi = mtl.parse('(start U[0, 21] success)')
print(phi(data, time = None, quantitative=False))
# Output: [(0, True), (20, True)]

phi = mtl.parse('(start U[0, 20] success)')
print(phi(data, time = None, quantitative=False))
# Output: [(0, False), (20, True)]
```

**Comment by mvcisback** [comment]
Hi @xian49930 ,

I think it's very possible that timed until might not work as expected. I believe that paper I read the semantics from which I implemented it a while ago had a bug. The current semantics from from this snippet

![2020-04-14_14-08](https://user-images.githubusercontent.com/388723/79274499-85c9b780-7e59-11ea-9f70-bbd81edd03a5.png)

, but looking back, I think this syntactic rewrite may be incorrect.

I can certainly take a look, but it'll probably be next week or so.

**Comment by sokolsky** [comment]
I don't think it has to do with the representation of timed until; the formula seems fine at the first glance.  Rather, the problem seems to be the way it is evaluated.  Here is an experiment.  

Consider: 
phi = mtl.parse('(~start U[0,120] success)')

data = {
    'start': [(0,True), (200,False)], 
    'success': [(0,False), (300,True)]
}

Intuitively, phi should be true at time 200.   Let's try.

>>> print(phi(data, time = None, quantitative=False))
[(0, False), (200, False), (300, True)]

Not what I expected.  Let's look at your decomposition:

>>> phi
(~G[0.0,120.0]~success & G[0,0.0]~start & G[0.0,0.0]((~start W success) & ~G~success))

Let's try the pieces separately:
>>> phi1 = mtl.parse('G[0,0]~start')
>>> phi2 = mtl.parse('F[0,120]success')
>>> phi3 = mtl.parse('G[0,0]((~start W success) & F success))')

>>> print(phi(data, time = None, quantitative=False))
[(0, False), (200, False), (300, True)]
>>> print(phi1(data, time = None, quantitative=False))
[(0, False), (200, True)]
>>> print(phi2(data, time = None, quantitative=False))
[(0, False), (300, True)]
>>> print(phi3(data, time = None, quantitative=False))
[(0, False), (200, True), (300, True)]

Everything seems fine.  Except phi2 is not evaluated at 200, or anywhere in between 0 and 300.  It looks a little suspicious, because phi2 becomes true at 80, right?  Well, let's force it to be evaluated:

data = {
    'start': [(0,True), (200,False)], 
    'success': [(0,False), (200,False), (300,True)]
}

>>> print(phi1(data, time = None, quantitative=False))
[(0, False), (200, True)]
>>> print(phi2(data, time = None, quantitative=False))
[(0, False), (200, True), (300, True)]
>>> print(phi3(data, time = None, quantitative=False))
[(0, False), (200, True), (300, True)]
>>> **print(phi(data, time = None, quantitative=False))
[(0, False), (200, True), (300, True)]**

Now we get the expected result.  So either we misunderstand your trace semantics, or there is something wrong with evaluation.

**Comment by mvcisback** [comment]
@sokolsky Thanks for the detailed analysis!

I'll take a look as soon as I can!

**Comment by Gaudeval** [comment]
@sokolsky @xian49930  After a quick fix I get the following. Are you happy with the results? Please note the use of `dt` to specify the discrete time step.

```python
import mtl


data = {
'start': [(0,True), (200,False)],
'success': [(0,False), (300,True)]
}
phi = mtl.parse('(~start U[0,120] success)')
print(phi(data, time = None, quantitative=False, dt=1))
# [(0, False), (181.0, False), (200, True), (300, True)]

data = {
    'start': [(0, True), (1, False), (5, True), (6, True)],
    'success': [(0, False), (20, True)]
}
phi1 = mtl.parse('(start U[0,20] success)')
print(phi1(data, time = None, quantitative=False, dt=1))
# [(0, False), (1.0, False), (5, True), (6, True), (20, True)]

data = {
    'start': [(0,True), (200,False)],
    'success': [(0,False), (300,True)]
}
phi2 = mtl.parse('F[0,120]success')
print(phi2(data, time = None, quantitative=False, dt=1))
# [(0, False), (181.0, True), (300, True)
```

The issue relates to #221 and a similar solution may apply. Evaluation only occurs at existing data points `(0, 300)` instead of pivot points where the property may change `(0, 181, 300)` . The fix creates those pivot points in the signal before evaluation based on the interval.
